name: Commit message check (PR)
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json
